[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "easydone"
version = "0.2.0"
description = "A CLI app made with python for easy tasks management."
readme = "README.md"
requires-python = ">=3.9"
authors = [{name = "Pedro Alberto Rosquete Ares", email = "rosquetearespedro06@gmail.com"}]
license = { file = "LICENSE" }
dependencies = ['rich>=13.0']

[project.urls]
Documentation = "https://github.com/prares-dev/easydone.git"
Homepage = "https://github.com/prares-dev/easydone.git"
Repository = "https://github.com/prares-dev/easydone.git"

[project.scripts]
easydone = "easydone.__main__:main"

[project.optional-dependencies]
dev = ["pytest>=8.0",]

[tool.setuptools.packages.find]
include = ["easydone*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-ra"