[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "easydone-task-tracker"
version = "0.2.0"
description = "A simple command-line task tracker."
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Pedro A. Rosquete Ares", email = "rosquetearespedro06@gmail.com"}]
license = { file = "LICENSE" }
dependencies = ['rich>=13.0']

[project.urls]
Documentation = "https://github.com/prares-dev/easydone-task-tracker.git"
Homepage = "https://github.com/prares-dev/easydone-task-tracker.git"
Repository = "https://github.com/prares-dev/easydone-task-tracker.git"

[project.scripts]
easydone = "easydone.__main__:main"

[project.optional-dependencies]
dev = ["pytest>=8.0",]

[tool.setuptools.packages.find]
include = ["easydone*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-ra"